services:
  database:
    image: imresamu/postgis:17-3.5.2-alpine3.21
    restart: always
    environment:
      POSTGRES_USER: navtrack
      POSTGRES_PASSWORD: navtrack
    volumes:
      - navtrack-database:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  navtrack-database:
