/*
 * Generated by orval v5.5.10 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0
 */
import type { AssetModel } from './assetModel';

export interface AssetListModel {
  items: AssetModel[];
}
