/*
 * Generated by orval v5.5.10 🍺
 * Do not edit manually.
 * Navtrack.App
 * OpenAPI spec version: 1.0
 */
import type { DeviceResponseModel } from './deviceResponseModel';
import type { Location } from './location';

export interface Asset {
  id: string;
  readonly shortId: string;
  name: string;
  readonly online: boolean;
  readonly maxSpeed: number;
  activeDevice?: DeviceResponseModel;
  devices?: DeviceResponseModel[] | null;
  location?: Location;
}
