/*
 * Generated by orval v5.5.10 🍺
 * Do not edit manually.
 * Navtrack.App
 * OpenAPI spec version: 1.0
 */
import type { UnitsType } from './unitsType';

export interface CurrentUser {
  id: string;
  email: string;
  units: UnitsType;
}
