/*
 * Generated by orval v5.5.10 🍺
 * Do not edit manually.
 * Navtrack.App
 * OpenAPI spec version: 1.0
 */
import type { ObjectId } from './objectId';
import type { DeviceTypeModel } from './deviceTypeModel';

export interface DeviceResponseModel {
  id?: ObjectId;
  assetId?: number;
  deviceId?: string | null;
  deviceType?: DeviceTypeModel;
  locationsCount?: number;
  isActive?: boolean;
}
