/*
 * Generated by orval v5.5.10 🍺
 * Do not edit manually.
 * Navtrack.App
 * OpenAPI spec version: 1.0
 */
import type { ValidationErrorModel } from './validationErrorModel';

export interface ErrorModel {
  code?: string | null;
  message?: string | null;
  validationErrors?: ValidationErrorModel[] | null;
}
