/*
 * Generated by orval v5.5.10 🍺
 * Do not edit manually.
 * Navtrack.App
 * OpenAPI spec version: 1.0
 */

export type GetAssetsAssetIdTripsParams = { MinAvgAltitude?: number; MaxAvgAltitude?: number; MinAvgSpeed?: number; MaxAvgSpeed?: number; MinDuration?: number; MaxDuration?: number; Latitude?: number; Longitude?: number; Radius?: number; StartDate?: string; EndDate?: string };
