/*
 * Generated by orval v5.5.10 🍺
 * Do not edit manually.
 * Navtrack.App
 * OpenAPI spec version: 1.0
 */

export type GetAssetsAssetIdLocationsParams = { StartDate?: string; EndDate?: string; MinAltitude?: number; MaxAltitude?: number; MinSpeed?: number; MaxSpeed?: number; Latitude?: number; Longitude?: number; Radius?: number; page?: number; size?: number };
