/*
 * Generated by orval v5.5.10 🍺
 * Do not edit manually.
 * Navtrack.App
 * OpenAPI spec version: 1.0
 */
import type { Location } from './location';

export interface LocationList {
  items: Location[];
  readonly averageSpeed?: number | null;
  readonly averageAltitude?: number | null;
}
