/*
 * Generated by orval v5.5.10 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0
 */
import type { LocationModel } from './locationModel';

export interface LocationListModel {
  items: LocationModel[];
  readonly averageSpeed?: number | null;
  readonly averageAltitude?: number | null;
}
