/*
 * Generated by orval v5.5.10 🍺
 * Do not edit manually.
 * Navtrack.App
 * OpenAPI spec version: 1.0
 */

export interface ObjectId {
  timestamp?: number;
  machine?: number;
  pid?: number;
  increment?: number;
  readonly creationTime?: string;
}
