/*
 * Generated by orval v5.5.10 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0
 */
import type { LocationModel } from './locationModel';

export interface TripModel {
  startLocation: LocationModel;
  endLocation: LocationModel;
  locations: LocationModel[];
  distance: number;
  duration: number;
  maxSpeed?: number | null;
  averageSpeed?: number | null;
  averageAltitude?: number | null;
}
