/*
 * Generated by orval v5.5.10 🍺
 * Do not edit manually.
 * Navtrack.App
 * OpenAPI spec version: 1.0
 */
import type { Trip } from './trip';

export interface TripList {
  items: Trip[];
  readonly totalDistance: number;
  readonly totalDuration: number;
  readonly totalLocations: number;
  readonly totalAvgSpeed: number;
  readonly totalAvgAltitude: number;
}
