/*
 * Generated by orval v5.5.10 🍺
 * Do not edit manually.
 * Navtrack.App
 * OpenAPI spec version: 1.0
 */
import type { Location } from './location';

export interface Trip {
  startLocation: Location;
  endLocation: Location;
  locations: Location[];
  distance: number;
  duration: number;
  maxSpeed?: number | null;
  averageSpeed?: number | null;
  averageAltitude?: number | null;
}
