/*
 * Generated by orval v5.5.10 🍺
 * Do not edit manually.
 * Navtrack.App
 * OpenAPI spec version: 1.0
 */

export type UnitsType = 0 | 1;


export const UnitsType = {
  NUMBER_0: 0 as UnitsType,
  NUMBER_1: 1 as UnitsType,
};
