/*
 * Generated by orval v5.5.10 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0
 */

export interface ValidationErrorModel {
  code?: string | null;
  message?: string | null;
  propertyName: string;
}
