export const Paths = {
  AssetPattern: "/assets/:id/*",
  AssetsAdd: "/assets/add",
  AssetsAlerts: "/assets/:id/alerts",
  AssetsDashboard: "/assets/:id/dashboard",
  AssetsLive: "/assets/:id/live",
  AssetsLog: "/assets/:id/log",
  AssetsReports: "/assets/:id/reports",
  AssetsSettings: "/assets/:id/settings",
  AssetsSettingsAccess: "/assets/:id/settings/access",
  AssetsSettingsDevice: "/assets/:id/settings/device",
  AssetsTrips: "/assets/:id/trips",
  ForgotPassword: "/forgotpassword",
  Home: "/",
  Register: "/register",
  Reports: "/reports",
  ResetPassword: "/resetpassword/:hash",
  SettingsAccount: "/settings/account",
  SettingsAuthentication: "/settings/authentication"
};
