/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from "@tanstack/react-query";
import type {
  AssetModel,
  AssetStatListModel,
  AssetsMessagesGetListParams,
  AssetsReportsGetDistanceReportParams,
  AssetsReportsGetFuelConsumptionReportParams,
  AssetsReportsGetTripReportParams,
  AssetsTripsGetListParams,
  ChangePasswordModel,
  CreateAccountModel,
  CreateAssetModel,
  CreateAssetUserModel,
  CreateOrUpdateAssetDeviceModel,
  CreateOrganizationModel,
  CreateOrganizationUserModel,
  CreateTeam,
  CreateTeamAsset,
  CreateTeamUser,
  CurrentUserModel,
  DistanceReportModel,
  Entity,
  ErrorModel,
  ForgotPasswordModel,
  FuelConsumptionReportModel,
  GeocodeReverseParams,
  ListModelOfAssetModel,
  ListModelOfAssetUserModel,
  ListModelOfDeviceModel,
  ListModelOfDeviceTypeModel,
  ListModelOfOrganizationModel,
  ListModelOfOrganizationUserModel,
  ListModelOfProtocolModel,
  ListModelOfTeam,
  ListModelOfTeamAssetModel,
  ListModelOfTeamUser,
  LocationModel,
  MessageList,
  OrganizationModel,
  ProblemDetails,
  ResetPasswordModel,
  Team,
  TripList,
  TripReportModel,
  UpdateAssetModel,
  UpdateOrganizationModel,
  UpdateOrganizationUserModel,
  UpdateTeam,
  UpdateTeamUser,
  UpdateUserModel
} from "./model";
import { authAxiosInstance } from "../axios/authAxiosInstance";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export const accountCreateAccount = (
  createAccountModel: CreateAccountModel
) => {
  return authAxiosInstance<void>({
    url: `/account`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createAccountModel
  });
};

export const getAccountCreateAccountMutationOptions = <
  TError = ErrorModel,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof accountCreateAccount>>,
    TError,
    { data: CreateAccountModel },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof accountCreateAccount>>,
  TError,
  { data: CreateAccountModel },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof accountCreateAccount>>,
    { data: CreateAccountModel }
  > = (props) => {
    const { data } = props ?? {};

    return accountCreateAccount(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AccountCreateAccountMutationResult = NonNullable<
  Awaited<ReturnType<typeof accountCreateAccount>>
>;
export type AccountCreateAccountMutationBody = CreateAccountModel;
export type AccountCreateAccountMutationError = ErrorModel;

export const useAccountCreateAccount = <
  TError = ErrorModel,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof accountCreateAccount>>,
    TError,
    { data: CreateAccountModel },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof accountCreateAccount>>,
  TError,
  { data: CreateAccountModel },
  TContext
> => {
  const mutationOptions = getAccountCreateAccountMutationOptions(options);

  return useMutation(mutationOptions);
};

export const accountForgotPassword = (
  forgotPasswordModel: ForgotPasswordModel
) => {
  return authAxiosInstance<void>({
    url: `/account/forgot-password`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: forgotPasswordModel
  });
};

export const getAccountForgotPasswordMutationOptions = <
  TError = ErrorModel,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof accountForgotPassword>>,
    TError,
    { data: ForgotPasswordModel },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof accountForgotPassword>>,
  TError,
  { data: ForgotPasswordModel },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof accountForgotPassword>>,
    { data: ForgotPasswordModel }
  > = (props) => {
    const { data } = props ?? {};

    return accountForgotPassword(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AccountForgotPasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof accountForgotPassword>>
>;
export type AccountForgotPasswordMutationBody = ForgotPasswordModel;
export type AccountForgotPasswordMutationError = ErrorModel;

export const useAccountForgotPassword = <
  TError = ErrorModel,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof accountForgotPassword>>,
    TError,
    { data: ForgotPasswordModel },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof accountForgotPassword>>,
  TError,
  { data: ForgotPasswordModel },
  TContext
> => {
  const mutationOptions = getAccountForgotPasswordMutationOptions(options);

  return useMutation(mutationOptions);
};

export const accountResetPassword = (
  resetPasswordModel: ResetPasswordModel
) => {
  return authAxiosInstance<void>({
    url: `/account/reset-password`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: resetPasswordModel
  });
};

export const getAccountResetPasswordMutationOptions = <
  TError = ErrorModel,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof accountResetPassword>>,
    TError,
    { data: ResetPasswordModel },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof accountResetPassword>>,
  TError,
  { data: ResetPasswordModel },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof accountResetPassword>>,
    { data: ResetPasswordModel }
  > = (props) => {
    const { data } = props ?? {};

    return accountResetPassword(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AccountResetPasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof accountResetPassword>>
>;
export type AccountResetPasswordMutationBody = ResetPasswordModel;
export type AccountResetPasswordMutationError = ErrorModel;

export const useAccountResetPassword = <
  TError = ErrorModel,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof accountResetPassword>>,
    TError,
    { data: ResetPasswordModel },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof accountResetPassword>>,
  TError,
  { data: ResetPasswordModel },
  TContext
> => {
  const mutationOptions = getAccountResetPasswordMutationOptions(options);

  return useMutation(mutationOptions);
};

export const assetsGetList = (organizationId: string, signal?: AbortSignal) => {
  return authAxiosInstance<ListModelOfAssetModel>({
    url: `/organizations/${organizationId}/assets`,
    method: "GET",
    signal
  });
};

export const getAssetsGetListQueryKey = (organizationId: string) => {
  return [`/organizations/${organizationId}/assets`] as const;
};

export const getAssetsGetListQueryOptions = <
  TData = Awaited<ReturnType<typeof assetsGetList>>,
  TError = unknown
>(
  organizationId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof assetsGetList>>,
      TError,
      TData
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAssetsGetListQueryKey(organizationId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof assetsGetList>>> = ({
    signal
  }) => assetsGetList(organizationId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!organizationId,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof assetsGetList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AssetsGetListQueryResult = NonNullable<
  Awaited<ReturnType<typeof assetsGetList>>
>;
export type AssetsGetListQueryError = unknown;

export const useAssetsGetList = <
  TData = Awaited<ReturnType<typeof assetsGetList>>,
  TError = unknown
>(
  organizationId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof assetsGetList>>,
      TError,
      TData
    >;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAssetsGetListQueryOptions(organizationId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const assetsCreate = (
  organizationId: string,
  createAssetModel: CreateAssetModel
) => {
  return authAxiosInstance<Entity>({
    url: `/organizations/${organizationId}/assets`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createAssetModel
  });
};

export const getAssetsCreateMutationOptions = <
  TError = ErrorModel,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof assetsCreate>>,
    TError,
    { organizationId: string; data: CreateAssetModel },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof assetsCreate>>,
  TError,
  { organizationId: string; data: CreateAssetModel },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof assetsCreate>>,
    { organizationId: string; data: CreateAssetModel }
  > = (props) => {
    const { organizationId, data } = props ?? {};

    return assetsCreate(organizationId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AssetsCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof assetsCreate>>
>;
export type AssetsCreateMutationBody = CreateAssetModel;
export type AssetsCreateMutationError = ErrorModel;

export const useAssetsCreate = <
  TError = ErrorModel,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof assetsCreate>>,
    TError,
    { organizationId: string; data: CreateAssetModel },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof assetsCreate>>,
  TError,
  { organizationId: string; data: CreateAssetModel },
  TContext
> => {
  const mutationOptions = getAssetsCreateMutationOptions(options);

  return useMutation(mutationOptions);
};

export const assetsGet = (assetId: string, signal?: AbortSignal) => {
  return authAxiosInstance<AssetModel>({
    url: `/assets/${assetId}`,
    method: "GET",
    signal
  });
};

export const getAssetsGetQueryKey = (assetId: string) => {
  return [`/assets/${assetId}`] as const;
};

export const getAssetsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof assetsGet>>,
  TError = ProblemDetails
>(
  assetId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof assetsGet>>,
      TError,
      TData
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAssetsGetQueryKey(assetId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof assetsGet>>> = ({
    signal
  }) => assetsGet(assetId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!assetId,
    ...queryOptions
  } as UseQueryOptions<Awaited<ReturnType<typeof assetsGet>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type AssetsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof assetsGet>>
>;
export type AssetsGetQueryError = ProblemDetails;

export const useAssetsGet = <
  TData = Awaited<ReturnType<typeof assetsGet>>,
  TError = ProblemDetails
>(
  assetId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof assetsGet>>,
      TError,
      TData
    >;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAssetsGetQueryOptions(assetId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const assetsUpdate = (
  assetId: string,
  updateAssetModel: UpdateAssetModel
) => {
  return authAxiosInstance<void>({
    url: `/assets/${assetId}`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: updateAssetModel
  });
};

export const getAssetsUpdateMutationOptions = <
  TError = ErrorModel | ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof assetsUpdate>>,
    TError,
    { assetId: string; data: UpdateAssetModel },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof assetsUpdate>>,
  TError,
  { assetId: string; data: UpdateAssetModel },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof assetsUpdate>>,
    { assetId: string; data: UpdateAssetModel }
  > = (props) => {
    const { assetId, data } = props ?? {};

    return assetsUpdate(assetId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AssetsUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof assetsUpdate>>
>;
export type AssetsUpdateMutationBody = UpdateAssetModel;
export type AssetsUpdateMutationError = ErrorModel | ProblemDetails;

export const useAssetsUpdate = <
  TError = ErrorModel | ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof assetsUpdate>>,
    TError,
    { assetId: string; data: UpdateAssetModel },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof assetsUpdate>>,
  TError,
  { assetId: string; data: UpdateAssetModel },
  TContext
> => {
  const mutationOptions = getAssetsUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};

export const assetsDelete = (assetId: string) => {
  return authAxiosInstance<void>({
    url: `/assets/${assetId}`,
    method: "DELETE"
  });
};

export const getAssetsDeleteMutationOptions = <
  TError = ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof assetsDelete>>,
    TError,
    { assetId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof assetsDelete>>,
  TError,
  { assetId: string },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof assetsDelete>>,
    { assetId: string }
  > = (props) => {
    const { assetId } = props ?? {};

    return assetsDelete(assetId);
  };

  return { mutationFn, ...mutationOptions };
};

export type AssetsDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof assetsDelete>>
>;

export type AssetsDeleteMutationError = ProblemDetails;

export const useAssetsDelete = <
  TError = ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof assetsDelete>>,
    TError,
    { assetId: string },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof assetsDelete>>,
  TError,
  { assetId: string },
  TContext
> => {
  const mutationOptions = getAssetsDeleteMutationOptions(options);

  return useMutation(mutationOptions);
};

export const assetsDevicesGetList = (assetId: string, signal?: AbortSignal) => {
  return authAxiosInstance<ListModelOfDeviceModel>({
    url: `/assets/${assetId}/devices`,
    method: "GET",
    signal
  });
};

export const getAssetsDevicesGetListQueryKey = (assetId: string) => {
  return [`/assets/${assetId}/devices`] as const;
};

export const getAssetsDevicesGetListQueryOptions = <
  TData = Awaited<ReturnType<typeof assetsDevicesGetList>>,
  TError = ProblemDetails
>(
  assetId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof assetsDevicesGetList>>,
      TError,
      TData
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAssetsDevicesGetListQueryKey(assetId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof assetsDevicesGetList>>
  > = ({ signal }) => assetsDevicesGetList(assetId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!assetId,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof assetsDevicesGetList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AssetsDevicesGetListQueryResult = NonNullable<
  Awaited<ReturnType<typeof assetsDevicesGetList>>
>;
export type AssetsDevicesGetListQueryError = ProblemDetails;

export const useAssetsDevicesGetList = <
  TData = Awaited<ReturnType<typeof assetsDevicesGetList>>,
  TError = ProblemDetails
>(
  assetId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof assetsDevicesGetList>>,
      TError,
      TData
    >;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAssetsDevicesGetListQueryOptions(assetId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const assetsDevicesCreateOrUpdate = (
  assetId: string,
  createOrUpdateAssetDeviceModel: CreateOrUpdateAssetDeviceModel
) => {
  return authAxiosInstance<void>({
    url: `/assets/${assetId}/devices`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createOrUpdateAssetDeviceModel
  });
};

export const getAssetsDevicesCreateOrUpdateMutationOptions = <
  TError = ErrorModel | ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof assetsDevicesCreateOrUpdate>>,
    TError,
    { assetId: string; data: CreateOrUpdateAssetDeviceModel },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof assetsDevicesCreateOrUpdate>>,
  TError,
  { assetId: string; data: CreateOrUpdateAssetDeviceModel },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof assetsDevicesCreateOrUpdate>>,
    { assetId: string; data: CreateOrUpdateAssetDeviceModel }
  > = (props) => {
    const { assetId, data } = props ?? {};

    return assetsDevicesCreateOrUpdate(assetId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AssetsDevicesCreateOrUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof assetsDevicesCreateOrUpdate>>
>;
export type AssetsDevicesCreateOrUpdateMutationBody =
  CreateOrUpdateAssetDeviceModel;
export type AssetsDevicesCreateOrUpdateMutationError =
  | ErrorModel
  | ProblemDetails;

export const useAssetsDevicesCreateOrUpdate = <
  TError = ErrorModel | ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof assetsDevicesCreateOrUpdate>>,
    TError,
    { assetId: string; data: CreateOrUpdateAssetDeviceModel },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof assetsDevicesCreateOrUpdate>>,
  TError,
  { assetId: string; data: CreateOrUpdateAssetDeviceModel },
  TContext
> => {
  const mutationOptions =
    getAssetsDevicesCreateOrUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};

export const assetsDevicesDelete = (assetId: string, deviceId: string) => {
  return authAxiosInstance<void>({
    url: `/assets/${assetId}/devices/${deviceId}`,
    method: "DELETE"
  });
};

export const getAssetsDevicesDeleteMutationOptions = <
  TError = ErrorModel | ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof assetsDevicesDelete>>,
    TError,
    { assetId: string; deviceId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof assetsDevicesDelete>>,
  TError,
  { assetId: string; deviceId: string },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof assetsDevicesDelete>>,
    { assetId: string; deviceId: string }
  > = (props) => {
    const { assetId, deviceId } = props ?? {};

    return assetsDevicesDelete(assetId, deviceId);
  };

  return { mutationFn, ...mutationOptions };
};

export type AssetsDevicesDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof assetsDevicesDelete>>
>;

export type AssetsDevicesDeleteMutationError = ErrorModel | ProblemDetails;

export const useAssetsDevicesDelete = <
  TError = ErrorModel | ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof assetsDevicesDelete>>,
    TError,
    { assetId: string; deviceId: string },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof assetsDevicesDelete>>,
  TError,
  { assetId: string; deviceId: string },
  TContext
> => {
  const mutationOptions = getAssetsDevicesDeleteMutationOptions(options);

  return useMutation(mutationOptions);
};

export const assetsMessagesGetList = (
  assetId: string,
  params?: AssetsMessagesGetListParams,
  signal?: AbortSignal
) => {
  return authAxiosInstance<MessageList>({
    url: `/assets/${assetId}/messages`,
    method: "GET",
    params,
    signal
  });
};

export const getAssetsMessagesGetListQueryKey = (
  assetId: string,
  params?: AssetsMessagesGetListParams
) => {
  return [`/assets/${assetId}/messages`, ...(params ? [params] : [])] as const;
};

export const getAssetsMessagesGetListQueryOptions = <
  TData = Awaited<ReturnType<typeof assetsMessagesGetList>>,
  TError = ProblemDetails
>(
  assetId: string,
  params?: AssetsMessagesGetListParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof assetsMessagesGetList>>,
      TError,
      TData
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAssetsMessagesGetListQueryKey(assetId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof assetsMessagesGetList>>
  > = ({ signal }) => assetsMessagesGetList(assetId, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!assetId,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof assetsMessagesGetList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AssetsMessagesGetListQueryResult = NonNullable<
  Awaited<ReturnType<typeof assetsMessagesGetList>>
>;
export type AssetsMessagesGetListQueryError = ProblemDetails;

export const useAssetsMessagesGetList = <
  TData = Awaited<ReturnType<typeof assetsMessagesGetList>>,
  TError = ProblemDetails
>(
  assetId: string,
  params?: AssetsMessagesGetListParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof assetsMessagesGetList>>,
      TError,
      TData
    >;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAssetsMessagesGetListQueryOptions(
    assetId,
    params,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const assetsReportsGetDistanceReport = (
  assetId: string,
  params?: AssetsReportsGetDistanceReportParams,
  signal?: AbortSignal
) => {
  return authAxiosInstance<DistanceReportModel>({
    url: `/assets/${assetId}/reports/distance`,
    method: "GET",
    params,
    signal
  });
};

export const getAssetsReportsGetDistanceReportQueryKey = (
  assetId: string,
  params?: AssetsReportsGetDistanceReportParams
) => {
  return [
    `/assets/${assetId}/reports/distance`,
    ...(params ? [params] : [])
  ] as const;
};

export const getAssetsReportsGetDistanceReportQueryOptions = <
  TData = Awaited<ReturnType<typeof assetsReportsGetDistanceReport>>,
  TError = ProblemDetails
>(
  assetId: string,
  params?: AssetsReportsGetDistanceReportParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof assetsReportsGetDistanceReport>>,
      TError,
      TData
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getAssetsReportsGetDistanceReportQueryKey(assetId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof assetsReportsGetDistanceReport>>
  > = ({ signal }) => assetsReportsGetDistanceReport(assetId, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!assetId,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof assetsReportsGetDistanceReport>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AssetsReportsGetDistanceReportQueryResult = NonNullable<
  Awaited<ReturnType<typeof assetsReportsGetDistanceReport>>
>;
export type AssetsReportsGetDistanceReportQueryError = ProblemDetails;

export const useAssetsReportsGetDistanceReport = <
  TData = Awaited<ReturnType<typeof assetsReportsGetDistanceReport>>,
  TError = ProblemDetails
>(
  assetId: string,
  params?: AssetsReportsGetDistanceReportParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof assetsReportsGetDistanceReport>>,
      TError,
      TData
    >;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAssetsReportsGetDistanceReportQueryOptions(
    assetId,
    params,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const assetsReportsGetFuelConsumptionReport = (
  assetId: string,
  params?: AssetsReportsGetFuelConsumptionReportParams,
  signal?: AbortSignal
) => {
  return authAxiosInstance<FuelConsumptionReportModel>({
    url: `/assets/${assetId}/reports/fuel-consumption`,
    method: "GET",
    params,
    signal
  });
};

export const getAssetsReportsGetFuelConsumptionReportQueryKey = (
  assetId: string,
  params?: AssetsReportsGetFuelConsumptionReportParams
) => {
  return [
    `/assets/${assetId}/reports/fuel-consumption`,
    ...(params ? [params] : [])
  ] as const;
};

export const getAssetsReportsGetFuelConsumptionReportQueryOptions = <
  TData = Awaited<ReturnType<typeof assetsReportsGetFuelConsumptionReport>>,
  TError = ProblemDetails
>(
  assetId: string,
  params?: AssetsReportsGetFuelConsumptionReportParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof assetsReportsGetFuelConsumptionReport>>,
      TError,
      TData
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getAssetsReportsGetFuelConsumptionReportQueryKey(assetId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof assetsReportsGetFuelConsumptionReport>>
  > = ({ signal }) =>
    assetsReportsGetFuelConsumptionReport(assetId, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!assetId,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof assetsReportsGetFuelConsumptionReport>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AssetsReportsGetFuelConsumptionReportQueryResult = NonNullable<
  Awaited<ReturnType<typeof assetsReportsGetFuelConsumptionReport>>
>;
export type AssetsReportsGetFuelConsumptionReportQueryError = ProblemDetails;

export const useAssetsReportsGetFuelConsumptionReport = <
  TData = Awaited<ReturnType<typeof assetsReportsGetFuelConsumptionReport>>,
  TError = ProblemDetails
>(
  assetId: string,
  params?: AssetsReportsGetFuelConsumptionReportParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof assetsReportsGetFuelConsumptionReport>>,
      TError,
      TData
    >;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAssetsReportsGetFuelConsumptionReportQueryOptions(
    assetId,
    params,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const assetsReportsGetTripReport = (
  assetId: string,
  params?: AssetsReportsGetTripReportParams,
  signal?: AbortSignal
) => {
  return authAxiosInstance<TripReportModel>({
    url: `/assets/${assetId}/reports/trips`,
    method: "GET",
    params,
    signal
  });
};

export const getAssetsReportsGetTripReportQueryKey = (
  assetId: string,
  params?: AssetsReportsGetTripReportParams
) => {
  return [
    `/assets/${assetId}/reports/trips`,
    ...(params ? [params] : [])
  ] as const;
};

export const getAssetsReportsGetTripReportQueryOptions = <
  TData = Awaited<ReturnType<typeof assetsReportsGetTripReport>>,
  TError = ProblemDetails
>(
  assetId: string,
  params?: AssetsReportsGetTripReportParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof assetsReportsGetTripReport>>,
      TError,
      TData
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getAssetsReportsGetTripReportQueryKey(assetId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof assetsReportsGetTripReport>>
  > = ({ signal }) => assetsReportsGetTripReport(assetId, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!assetId,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof assetsReportsGetTripReport>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AssetsReportsGetTripReportQueryResult = NonNullable<
  Awaited<ReturnType<typeof assetsReportsGetTripReport>>
>;
export type AssetsReportsGetTripReportQueryError = ProblemDetails;

export const useAssetsReportsGetTripReport = <
  TData = Awaited<ReturnType<typeof assetsReportsGetTripReport>>,
  TError = ProblemDetails
>(
  assetId: string,
  params?: AssetsReportsGetTripReportParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof assetsReportsGetTripReport>>,
      TError,
      TData
    >;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAssetsReportsGetTripReportQueryOptions(
    assetId,
    params,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const assetsStatsGet = (assetId: string, signal?: AbortSignal) => {
  return authAxiosInstance<AssetStatListModel>({
    url: `/assets/${assetId}/stats`,
    method: "GET",
    signal
  });
};

export const getAssetsStatsGetQueryKey = (assetId: string) => {
  return [`/assets/${assetId}/stats`] as const;
};

export const getAssetsStatsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof assetsStatsGet>>,
  TError = ProblemDetails
>(
  assetId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof assetsStatsGet>>,
      TError,
      TData
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAssetsStatsGetQueryKey(assetId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof assetsStatsGet>>> = ({
    signal
  }) => assetsStatsGet(assetId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!assetId,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof assetsStatsGet>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AssetsStatsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof assetsStatsGet>>
>;
export type AssetsStatsGetQueryError = ProblemDetails;

export const useAssetsStatsGet = <
  TData = Awaited<ReturnType<typeof assetsStatsGet>>,
  TError = ProblemDetails
>(
  assetId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof assetsStatsGet>>,
      TError,
      TData
    >;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAssetsStatsGetQueryOptions(assetId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const assetsTripsGetList = (
  assetId: string,
  params?: AssetsTripsGetListParams,
  signal?: AbortSignal
) => {
  return authAxiosInstance<TripList>({
    url: `/assets/${assetId}/trips`,
    method: "GET",
    params,
    signal
  });
};

export const getAssetsTripsGetListQueryKey = (
  assetId: string,
  params?: AssetsTripsGetListParams
) => {
  return [`/assets/${assetId}/trips`, ...(params ? [params] : [])] as const;
};

export const getAssetsTripsGetListQueryOptions = <
  TData = Awaited<ReturnType<typeof assetsTripsGetList>>,
  TError = ProblemDetails
>(
  assetId: string,
  params?: AssetsTripsGetListParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof assetsTripsGetList>>,
      TError,
      TData
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAssetsTripsGetListQueryKey(assetId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof assetsTripsGetList>>
  > = ({ signal }) => assetsTripsGetList(assetId, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!assetId,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof assetsTripsGetList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AssetsTripsGetListQueryResult = NonNullable<
  Awaited<ReturnType<typeof assetsTripsGetList>>
>;
export type AssetsTripsGetListQueryError = ProblemDetails;

export const useAssetsTripsGetList = <
  TData = Awaited<ReturnType<typeof assetsTripsGetList>>,
  TError = ProblemDetails
>(
  assetId: string,
  params?: AssetsTripsGetListParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof assetsTripsGetList>>,
      TError,
      TData
    >;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAssetsTripsGetListQueryOptions(
    assetId,
    params,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const assetsUsersGetList = (assetId: string, signal?: AbortSignal) => {
  return authAxiosInstance<ListModelOfAssetUserModel>({
    url: `/assets/${assetId}/users`,
    method: "GET",
    signal
  });
};

export const getAssetsUsersGetListQueryKey = (assetId: string) => {
  return [`/assets/${assetId}/users`] as const;
};

export const getAssetsUsersGetListQueryOptions = <
  TData = Awaited<ReturnType<typeof assetsUsersGetList>>,
  TError = ProblemDetails
>(
  assetId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof assetsUsersGetList>>,
      TError,
      TData
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAssetsUsersGetListQueryKey(assetId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof assetsUsersGetList>>
  > = ({ signal }) => assetsUsersGetList(assetId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!assetId,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof assetsUsersGetList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AssetsUsersGetListQueryResult = NonNullable<
  Awaited<ReturnType<typeof assetsUsersGetList>>
>;
export type AssetsUsersGetListQueryError = ProblemDetails;

export const useAssetsUsersGetList = <
  TData = Awaited<ReturnType<typeof assetsUsersGetList>>,
  TError = ProblemDetails
>(
  assetId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof assetsUsersGetList>>,
      TError,
      TData
    >;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAssetsUsersGetListQueryOptions(assetId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const assetsUsersCreate = (
  assetId: string,
  createAssetUserModel: CreateAssetUserModel
) => {
  return authAxiosInstance<void>({
    url: `/assets/${assetId}/users`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createAssetUserModel
  });
};

export const getAssetsUsersCreateMutationOptions = <
  TError = ErrorModel | ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof assetsUsersCreate>>,
    TError,
    { assetId: string; data: CreateAssetUserModel },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof assetsUsersCreate>>,
  TError,
  { assetId: string; data: CreateAssetUserModel },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof assetsUsersCreate>>,
    { assetId: string; data: CreateAssetUserModel }
  > = (props) => {
    const { assetId, data } = props ?? {};

    return assetsUsersCreate(assetId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AssetsUsersCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof assetsUsersCreate>>
>;
export type AssetsUsersCreateMutationBody = CreateAssetUserModel;
export type AssetsUsersCreateMutationError = ErrorModel | ProblemDetails;

export const useAssetsUsersCreate = <
  TError = ErrorModel | ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof assetsUsersCreate>>,
    TError,
    { assetId: string; data: CreateAssetUserModel },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof assetsUsersCreate>>,
  TError,
  { assetId: string; data: CreateAssetUserModel },
  TContext
> => {
  const mutationOptions = getAssetsUsersCreateMutationOptions(options);

  return useMutation(mutationOptions);
};

export const assetsUsersDelete = (assetId: string, userId: string) => {
  return authAxiosInstance<void>({
    url: `/assets/${assetId}/users/${userId}`,
    method: "DELETE"
  });
};

export const getAssetsUsersDeleteMutationOptions = <
  TError = ErrorModel | ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof assetsUsersDelete>>,
    TError,
    { assetId: string; userId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof assetsUsersDelete>>,
  TError,
  { assetId: string; userId: string },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof assetsUsersDelete>>,
    { assetId: string; userId: string }
  > = (props) => {
    const { assetId, userId } = props ?? {};

    return assetsUsersDelete(assetId, userId);
  };

  return { mutationFn, ...mutationOptions };
};

export type AssetsUsersDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof assetsUsersDelete>>
>;

export type AssetsUsersDeleteMutationError = ErrorModel | ProblemDetails;

export const useAssetsUsersDelete = <
  TError = ErrorModel | ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof assetsUsersDelete>>,
    TError,
    { assetId: string; userId: string },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof assetsUsersDelete>>,
  TError,
  { assetId: string; userId: string },
  TContext
> => {
  const mutationOptions = getAssetsUsersDeleteMutationOptions(options);

  return useMutation(mutationOptions);
};

export const devicesGetList = (signal?: AbortSignal) => {
  return authAxiosInstance<ListModelOfDeviceTypeModel>({
    url: `/devices/types`,
    method: "GET",
    signal
  });
};

export const getDevicesGetListQueryKey = () => {
  return [`/devices/types`] as const;
};

export const getDevicesGetListQueryOptions = <
  TData = Awaited<ReturnType<typeof devicesGetList>>,
  TError = unknown
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof devicesGetList>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDevicesGetListQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof devicesGetList>>> = ({
    signal
  }) => devicesGetList(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof devicesGetList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type DevicesGetListQueryResult = NonNullable<
  Awaited<ReturnType<typeof devicesGetList>>
>;
export type DevicesGetListQueryError = unknown;

export const useDevicesGetList = <
  TData = Awaited<ReturnType<typeof devicesGetList>>,
  TError = unknown
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof devicesGetList>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getDevicesGetListQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const geocodeReverse = (
  params?: GeocodeReverseParams,
  signal?: AbortSignal
) => {
  return authAxiosInstance<LocationModel>({
    url: `/geocode/reverse`,
    method: "GET",
    params,
    signal
  });
};

export const getGeocodeReverseQueryKey = (params?: GeocodeReverseParams) => {
  return [`/geocode/reverse`, ...(params ? [params] : [])] as const;
};

export const getGeocodeReverseQueryOptions = <
  TData = Awaited<ReturnType<typeof geocodeReverse>>,
  TError = unknown
>(
  params?: GeocodeReverseParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof geocodeReverse>>,
      TError,
      TData
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGeocodeReverseQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof geocodeReverse>>> = ({
    signal
  }) => geocodeReverse(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof geocodeReverse>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GeocodeReverseQueryResult = NonNullable<
  Awaited<ReturnType<typeof geocodeReverse>>
>;
export type GeocodeReverseQueryError = unknown;

export const useGeocodeReverse = <
  TData = Awaited<ReturnType<typeof geocodeReverse>>,
  TError = unknown
>(
  params?: GeocodeReverseParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof geocodeReverse>>,
      TError,
      TData
    >;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGeocodeReverseQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const healthGet = (signal?: AbortSignal) => {
  return authAxiosInstance<void>({ url: `/health`, method: "GET", signal });
};

export const getHealthGetQueryKey = () => {
  return [`/health`] as const;
};

export const getHealthGetQueryOptions = <
  TData = Awaited<ReturnType<typeof healthGet>>,
  TError = unknown
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof healthGet>>, TError, TData>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthGetQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthGet>>> = ({
    signal
  }) => healthGet(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthGet>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthGet>>
>;
export type HealthGetQueryError = unknown;

export const useHealthGet = <
  TData = Awaited<ReturnType<typeof healthGet>>,
  TError = unknown
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof healthGet>>, TError, TData>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getHealthGetQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const organizationsList = (signal?: AbortSignal) => {
  return authAxiosInstance<ListModelOfOrganizationModel>({
    url: `/organizations`,
    method: "GET",
    signal
  });
};

export const getOrganizationsListQueryKey = () => {
  return [`/organizations`] as const;
};

export const getOrganizationsListQueryOptions = <
  TData = Awaited<ReturnType<typeof organizationsList>>,
  TError = ProblemDetails
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof organizationsList>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getOrganizationsListQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof organizationsList>>
  > = ({ signal }) => organizationsList(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof organizationsList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type OrganizationsListQueryResult = NonNullable<
  Awaited<ReturnType<typeof organizationsList>>
>;
export type OrganizationsListQueryError = ProblemDetails;

export const useOrganizationsList = <
  TData = Awaited<ReturnType<typeof organizationsList>>,
  TError = ProblemDetails
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof organizationsList>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getOrganizationsListQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const organizationsCreate = (
  createOrganizationModel: CreateOrganizationModel
) => {
  return authAxiosInstance<Entity>({
    url: `/organizations`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createOrganizationModel
  });
};

export const getOrganizationsCreateMutationOptions = <
  TError = ErrorModel,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizationsCreate>>,
    TError,
    { data: CreateOrganizationModel },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizationsCreate>>,
  TError,
  { data: CreateOrganizationModel },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizationsCreate>>,
    { data: CreateOrganizationModel }
  > = (props) => {
    const { data } = props ?? {};

    return organizationsCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizationsCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof organizationsCreate>>
>;
export type OrganizationsCreateMutationBody = CreateOrganizationModel;
export type OrganizationsCreateMutationError = ErrorModel;

export const useOrganizationsCreate = <
  TError = ErrorModel,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizationsCreate>>,
    TError,
    { data: CreateOrganizationModel },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof organizationsCreate>>,
  TError,
  { data: CreateOrganizationModel },
  TContext
> => {
  const mutationOptions = getOrganizationsCreateMutationOptions(options);

  return useMutation(mutationOptions);
};

export const organizationsGet = (
  organizationId: string,
  signal?: AbortSignal
) => {
  return authAxiosInstance<OrganizationModel>({
    url: `/organizations/${organizationId}`,
    method: "GET",
    signal
  });
};

export const getOrganizationsGetQueryKey = (organizationId: string) => {
  return [`/organizations/${organizationId}`] as const;
};

export const getOrganizationsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof organizationsGet>>,
  TError = ProblemDetails
>(
  organizationId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof organizationsGet>>,
      TError,
      TData
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getOrganizationsGetQueryKey(organizationId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof organizationsGet>>
  > = ({ signal }) => organizationsGet(organizationId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!organizationId,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof organizationsGet>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type OrganizationsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof organizationsGet>>
>;
export type OrganizationsGetQueryError = ProblemDetails;

export const useOrganizationsGet = <
  TData = Awaited<ReturnType<typeof organizationsGet>>,
  TError = ProblemDetails
>(
  organizationId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof organizationsGet>>,
      TError,
      TData
    >;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getOrganizationsGetQueryOptions(organizationId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const organizationsUpdate = (
  organizationId: string,
  updateOrganizationModel: UpdateOrganizationModel
) => {
  return authAxiosInstance<void>({
    url: `/organizations/${organizationId}`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: updateOrganizationModel
  });
};

export const getOrganizationsUpdateMutationOptions = <
  TError = ErrorModel | ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizationsUpdate>>,
    TError,
    { organizationId: string; data: UpdateOrganizationModel },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizationsUpdate>>,
  TError,
  { organizationId: string; data: UpdateOrganizationModel },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizationsUpdate>>,
    { organizationId: string; data: UpdateOrganizationModel }
  > = (props) => {
    const { organizationId, data } = props ?? {};

    return organizationsUpdate(organizationId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizationsUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof organizationsUpdate>>
>;
export type OrganizationsUpdateMutationBody = UpdateOrganizationModel;
export type OrganizationsUpdateMutationError = ErrorModel | ProblemDetails;

export const useOrganizationsUpdate = <
  TError = ErrorModel | ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizationsUpdate>>,
    TError,
    { organizationId: string; data: UpdateOrganizationModel },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof organizationsUpdate>>,
  TError,
  { organizationId: string; data: UpdateOrganizationModel },
  TContext
> => {
  const mutationOptions = getOrganizationsUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};

export const organizationsDelete = (organizationId: string) => {
  return authAxiosInstance<void>({
    url: `/organizations/${organizationId}`,
    method: "DELETE"
  });
};

export const getOrganizationsDeleteMutationOptions = <
  TError = ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizationsDelete>>,
    TError,
    { organizationId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizationsDelete>>,
  TError,
  { organizationId: string },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizationsDelete>>,
    { organizationId: string }
  > = (props) => {
    const { organizationId } = props ?? {};

    return organizationsDelete(organizationId);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizationsDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof organizationsDelete>>
>;

export type OrganizationsDeleteMutationError = ProblemDetails;

export const useOrganizationsDelete = <
  TError = ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizationsDelete>>,
    TError,
    { organizationId: string },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof organizationsDelete>>,
  TError,
  { organizationId: string },
  TContext
> => {
  const mutationOptions = getOrganizationsDeleteMutationOptions(options);

  return useMutation(mutationOptions);
};

export const organizationsUsersList = (
  organizationId: string,
  signal?: AbortSignal
) => {
  return authAxiosInstance<ListModelOfOrganizationUserModel>({
    url: `/organizations/${organizationId}/users`,
    method: "GET",
    signal
  });
};

export const getOrganizationsUsersListQueryKey = (organizationId: string) => {
  return [`/organizations/${organizationId}/users`] as const;
};

export const getOrganizationsUsersListQueryOptions = <
  TData = Awaited<ReturnType<typeof organizationsUsersList>>,
  TError = unknown
>(
  organizationId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof organizationsUsersList>>,
      TError,
      TData
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getOrganizationsUsersListQueryKey(organizationId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof organizationsUsersList>>
  > = ({ signal }) => organizationsUsersList(organizationId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!organizationId,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof organizationsUsersList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type OrganizationsUsersListQueryResult = NonNullable<
  Awaited<ReturnType<typeof organizationsUsersList>>
>;
export type OrganizationsUsersListQueryError = unknown;

export const useOrganizationsUsersList = <
  TData = Awaited<ReturnType<typeof organizationsUsersList>>,
  TError = unknown
>(
  organizationId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof organizationsUsersList>>,
      TError,
      TData
    >;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getOrganizationsUsersListQueryOptions(
    organizationId,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const organizationsUsersCreate = (
  organizationId: string,
  createOrganizationUserModel: CreateOrganizationUserModel
) => {
  return authAxiosInstance<void>({
    url: `/organizations/${organizationId}/users`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createOrganizationUserModel
  });
};

export const getOrganizationsUsersCreateMutationOptions = <
  TError = ErrorModel | ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizationsUsersCreate>>,
    TError,
    { organizationId: string; data: CreateOrganizationUserModel },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizationsUsersCreate>>,
  TError,
  { organizationId: string; data: CreateOrganizationUserModel },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizationsUsersCreate>>,
    { organizationId: string; data: CreateOrganizationUserModel }
  > = (props) => {
    const { organizationId, data } = props ?? {};

    return organizationsUsersCreate(organizationId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizationsUsersCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof organizationsUsersCreate>>
>;
export type OrganizationsUsersCreateMutationBody = CreateOrganizationUserModel;
export type OrganizationsUsersCreateMutationError = ErrorModel | ProblemDetails;

export const useOrganizationsUsersCreate = <
  TError = ErrorModel | ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizationsUsersCreate>>,
    TError,
    { organizationId: string; data: CreateOrganizationUserModel },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof organizationsUsersCreate>>,
  TError,
  { organizationId: string; data: CreateOrganizationUserModel },
  TContext
> => {
  const mutationOptions = getOrganizationsUsersCreateMutationOptions(options);

  return useMutation(mutationOptions);
};

export const organizationsUsersUpdate = (
  organizationId: string,
  userId: string,
  updateOrganizationUserModel: UpdateOrganizationUserModel
) => {
  return authAxiosInstance<void>({
    url: `/organizations/${organizationId}/users/${userId}`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: updateOrganizationUserModel
  });
};

export const getOrganizationsUsersUpdateMutationOptions = <
  TError = ErrorModel | ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizationsUsersUpdate>>,
    TError,
    {
      organizationId: string;
      userId: string;
      data: UpdateOrganizationUserModel;
    },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizationsUsersUpdate>>,
  TError,
  { organizationId: string; userId: string; data: UpdateOrganizationUserModel },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizationsUsersUpdate>>,
    {
      organizationId: string;
      userId: string;
      data: UpdateOrganizationUserModel;
    }
  > = (props) => {
    const { organizationId, userId, data } = props ?? {};

    return organizationsUsersUpdate(organizationId, userId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizationsUsersUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof organizationsUsersUpdate>>
>;
export type OrganizationsUsersUpdateMutationBody = UpdateOrganizationUserModel;
export type OrganizationsUsersUpdateMutationError = ErrorModel | ProblemDetails;

export const useOrganizationsUsersUpdate = <
  TError = ErrorModel | ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizationsUsersUpdate>>,
    TError,
    {
      organizationId: string;
      userId: string;
      data: UpdateOrganizationUserModel;
    },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof organizationsUsersUpdate>>,
  TError,
  { organizationId: string; userId: string; data: UpdateOrganizationUserModel },
  TContext
> => {
  const mutationOptions = getOrganizationsUsersUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};

export const organizationsUsersDelete = (
  organizationId: string,
  userId: string
) => {
  return authAxiosInstance<void>({
    url: `/organizations/${organizationId}/users/${userId}`,
    method: "DELETE"
  });
};

export const getOrganizationsUsersDeleteMutationOptions = <
  TError = ErrorModel | ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizationsUsersDelete>>,
    TError,
    { organizationId: string; userId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizationsUsersDelete>>,
  TError,
  { organizationId: string; userId: string },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizationsUsersDelete>>,
    { organizationId: string; userId: string }
  > = (props) => {
    const { organizationId, userId } = props ?? {};

    return organizationsUsersDelete(organizationId, userId);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizationsUsersDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof organizationsUsersDelete>>
>;

export type OrganizationsUsersDeleteMutationError = ErrorModel | ProblemDetails;

export const useOrganizationsUsersDelete = <
  TError = ErrorModel | ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizationsUsersDelete>>,
    TError,
    { organizationId: string; userId: string },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof organizationsUsersDelete>>,
  TError,
  { organizationId: string; userId: string },
  TContext
> => {
  const mutationOptions = getOrganizationsUsersDeleteMutationOptions(options);

  return useMutation(mutationOptions);
};

export const protocolsGetList = (signal?: AbortSignal) => {
  return authAxiosInstance<ListModelOfProtocolModel>({
    url: `/protocols`,
    method: "GET",
    signal
  });
};

export const getProtocolsGetListQueryKey = () => {
  return [`/protocols`] as const;
};

export const getProtocolsGetListQueryOptions = <
  TData = Awaited<ReturnType<typeof protocolsGetList>>,
  TError = unknown
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof protocolsGetList>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getProtocolsGetListQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof protocolsGetList>>
  > = ({ signal }) => protocolsGetList(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof protocolsGetList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ProtocolsGetListQueryResult = NonNullable<
  Awaited<ReturnType<typeof protocolsGetList>>
>;
export type ProtocolsGetListQueryError = unknown;

export const useProtocolsGetList = <
  TData = Awaited<ReturnType<typeof protocolsGetList>>,
  TError = unknown
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof protocolsGetList>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getProtocolsGetListQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const teamsAssetsList = (teamId: string, signal?: AbortSignal) => {
  return authAxiosInstance<ListModelOfTeamAssetModel>({
    url: `/teams/${teamId}/assets`,
    method: "GET",
    signal
  });
};

export const getTeamsAssetsListQueryKey = (teamId: string) => {
  return [`/teams/${teamId}/assets`] as const;
};

export const getTeamsAssetsListQueryOptions = <
  TData = Awaited<ReturnType<typeof teamsAssetsList>>,
  TError = ProblemDetails
>(
  teamId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof teamsAssetsList>>,
      TError,
      TData
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTeamsAssetsListQueryKey(teamId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof teamsAssetsList>>> = ({
    signal
  }) => teamsAssetsList(teamId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!teamId,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof teamsAssetsList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type TeamsAssetsListQueryResult = NonNullable<
  Awaited<ReturnType<typeof teamsAssetsList>>
>;
export type TeamsAssetsListQueryError = ProblemDetails;

export const useTeamsAssetsList = <
  TData = Awaited<ReturnType<typeof teamsAssetsList>>,
  TError = ProblemDetails
>(
  teamId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof teamsAssetsList>>,
      TError,
      TData
    >;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getTeamsAssetsListQueryOptions(teamId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const teamsAssetsCreate = (
  teamId: string,
  createTeamAsset: CreateTeamAsset
) => {
  return authAxiosInstance<void>({
    url: `/teams/${teamId}/assets`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createTeamAsset
  });
};

export const getTeamsAssetsCreateMutationOptions = <
  TError = ErrorModel | ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof teamsAssetsCreate>>,
    TError,
    { teamId: string; data: CreateTeamAsset },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof teamsAssetsCreate>>,
  TError,
  { teamId: string; data: CreateTeamAsset },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof teamsAssetsCreate>>,
    { teamId: string; data: CreateTeamAsset }
  > = (props) => {
    const { teamId, data } = props ?? {};

    return teamsAssetsCreate(teamId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type TeamsAssetsCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof teamsAssetsCreate>>
>;
export type TeamsAssetsCreateMutationBody = CreateTeamAsset;
export type TeamsAssetsCreateMutationError = ErrorModel | ProblemDetails;

export const useTeamsAssetsCreate = <
  TError = ErrorModel | ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof teamsAssetsCreate>>,
    TError,
    { teamId: string; data: CreateTeamAsset },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof teamsAssetsCreate>>,
  TError,
  { teamId: string; data: CreateTeamAsset },
  TContext
> => {
  const mutationOptions = getTeamsAssetsCreateMutationOptions(options);

  return useMutation(mutationOptions);
};

export const teamsAssetsDelete = (teamId: string, assetId: string) => {
  return authAxiosInstance<void>({
    url: `/teams/${teamId}/assets/${assetId}`,
    method: "DELETE"
  });
};

export const getTeamsAssetsDeleteMutationOptions = <
  TError = ErrorModel | ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof teamsAssetsDelete>>,
    TError,
    { teamId: string; assetId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof teamsAssetsDelete>>,
  TError,
  { teamId: string; assetId: string },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof teamsAssetsDelete>>,
    { teamId: string; assetId: string }
  > = (props) => {
    const { teamId, assetId } = props ?? {};

    return teamsAssetsDelete(teamId, assetId);
  };

  return { mutationFn, ...mutationOptions };
};

export type TeamsAssetsDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof teamsAssetsDelete>>
>;

export type TeamsAssetsDeleteMutationError = ErrorModel | ProblemDetails;

export const useTeamsAssetsDelete = <
  TError = ErrorModel | ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof teamsAssetsDelete>>,
    TError,
    { teamId: string; assetId: string },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof teamsAssetsDelete>>,
  TError,
  { teamId: string; assetId: string },
  TContext
> => {
  const mutationOptions = getTeamsAssetsDeleteMutationOptions(options);

  return useMutation(mutationOptions);
};

export const teamsGetList = (organizationId: string, signal?: AbortSignal) => {
  return authAxiosInstance<ListModelOfTeam>({
    url: `/organizations/${organizationId}/teams`,
    method: "GET",
    signal
  });
};

export const getTeamsGetListQueryKey = (organizationId: string) => {
  return [`/organizations/${organizationId}/teams`] as const;
};

export const getTeamsGetListQueryOptions = <
  TData = Awaited<ReturnType<typeof teamsGetList>>,
  TError = unknown
>(
  organizationId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof teamsGetList>>,
      TError,
      TData
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getTeamsGetListQueryKey(organizationId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof teamsGetList>>> = ({
    signal
  }) => teamsGetList(organizationId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!organizationId,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof teamsGetList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type TeamsGetListQueryResult = NonNullable<
  Awaited<ReturnType<typeof teamsGetList>>
>;
export type TeamsGetListQueryError = unknown;

export const useTeamsGetList = <
  TData = Awaited<ReturnType<typeof teamsGetList>>,
  TError = unknown
>(
  organizationId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof teamsGetList>>,
      TError,
      TData
    >;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getTeamsGetListQueryOptions(organizationId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const teamsCreate = (organizationId: string, createTeam: CreateTeam) => {
  return authAxiosInstance<Team>({
    url: `/organizations/${organizationId}/teams`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createTeam
  });
};

export const getTeamsCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof teamsCreate>>,
    TError,
    { organizationId: string; data: CreateTeam },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof teamsCreate>>,
  TError,
  { organizationId: string; data: CreateTeam },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof teamsCreate>>,
    { organizationId: string; data: CreateTeam }
  > = (props) => {
    const { organizationId, data } = props ?? {};

    return teamsCreate(organizationId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type TeamsCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof teamsCreate>>
>;
export type TeamsCreateMutationBody = CreateTeam;
export type TeamsCreateMutationError = unknown;

export const useTeamsCreate = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof teamsCreate>>,
    TError,
    { organizationId: string; data: CreateTeam },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof teamsCreate>>,
  TError,
  { organizationId: string; data: CreateTeam },
  TContext
> => {
  const mutationOptions = getTeamsCreateMutationOptions(options);

  return useMutation(mutationOptions);
};

export const teamsGet = (teamId: string, signal?: AbortSignal) => {
  return authAxiosInstance<Team>({
    url: `/teams/${teamId}`,
    method: "GET",
    signal
  });
};

export const getTeamsGetQueryKey = (teamId: string) => {
  return [`/teams/${teamId}`] as const;
};

export const getTeamsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof teamsGet>>,
  TError = unknown
>(
  teamId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof teamsGet>>,
      TError,
      TData
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTeamsGetQueryKey(teamId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof teamsGet>>> = ({
    signal
  }) => teamsGet(teamId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!teamId,
    ...queryOptions
  } as UseQueryOptions<Awaited<ReturnType<typeof teamsGet>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type TeamsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof teamsGet>>
>;
export type TeamsGetQueryError = unknown;

export const useTeamsGet = <
  TData = Awaited<ReturnType<typeof teamsGet>>,
  TError = unknown
>(
  teamId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof teamsGet>>,
      TError,
      TData
    >;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getTeamsGetQueryOptions(teamId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const teamsUpdate = (teamId: string, updateTeam: UpdateTeam) => {
  return authAxiosInstance<Blob>({
    url: `/teams/${teamId}`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: updateTeam,
    responseType: "blob"
  });
};

export const getTeamsUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof teamsUpdate>>,
    TError,
    { teamId: string; data: UpdateTeam },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof teamsUpdate>>,
  TError,
  { teamId: string; data: UpdateTeam },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof teamsUpdate>>,
    { teamId: string; data: UpdateTeam }
  > = (props) => {
    const { teamId, data } = props ?? {};

    return teamsUpdate(teamId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type TeamsUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof teamsUpdate>>
>;
export type TeamsUpdateMutationBody = UpdateTeam;
export type TeamsUpdateMutationError = unknown;

export const useTeamsUpdate = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof teamsUpdate>>,
    TError,
    { teamId: string; data: UpdateTeam },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof teamsUpdate>>,
  TError,
  { teamId: string; data: UpdateTeam },
  TContext
> => {
  const mutationOptions = getTeamsUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};

export const teamsDelete = (teamId: string) => {
  return authAxiosInstance<void>({ url: `/teams/${teamId}`, method: "DELETE" });
};

export const getTeamsDeleteMutationOptions = <
  TError = ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof teamsDelete>>,
    TError,
    { teamId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof teamsDelete>>,
  TError,
  { teamId: string },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof teamsDelete>>,
    { teamId: string }
  > = (props) => {
    const { teamId } = props ?? {};

    return teamsDelete(teamId);
  };

  return { mutationFn, ...mutationOptions };
};

export type TeamsDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof teamsDelete>>
>;

export type TeamsDeleteMutationError = ProblemDetails;

export const useTeamsDelete = <
  TError = ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof teamsDelete>>,
    TError,
    { teamId: string },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof teamsDelete>>,
  TError,
  { teamId: string },
  TContext
> => {
  const mutationOptions = getTeamsDeleteMutationOptions(options);

  return useMutation(mutationOptions);
};

export const teamsUsersList = (teamId: string, signal?: AbortSignal) => {
  return authAxiosInstance<ListModelOfTeamUser>({
    url: `/teams/${teamId}/users`,
    method: "GET",
    signal
  });
};

export const getTeamsUsersListQueryKey = (teamId: string) => {
  return [`/teams/${teamId}/users`] as const;
};

export const getTeamsUsersListQueryOptions = <
  TData = Awaited<ReturnType<typeof teamsUsersList>>,
  TError = ProblemDetails
>(
  teamId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof teamsUsersList>>,
      TError,
      TData
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTeamsUsersListQueryKey(teamId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof teamsUsersList>>> = ({
    signal
  }) => teamsUsersList(teamId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!teamId,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof teamsUsersList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type TeamsUsersListQueryResult = NonNullable<
  Awaited<ReturnType<typeof teamsUsersList>>
>;
export type TeamsUsersListQueryError = ProblemDetails;

export const useTeamsUsersList = <
  TData = Awaited<ReturnType<typeof teamsUsersList>>,
  TError = ProblemDetails
>(
  teamId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof teamsUsersList>>,
      TError,
      TData
    >;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getTeamsUsersListQueryOptions(teamId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const teamsUsersCreate = (
  teamId: string,
  createTeamUser: CreateTeamUser
) => {
  return authAxiosInstance<void>({
    url: `/teams/${teamId}/users`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createTeamUser
  });
};

export const getTeamsUsersCreateMutationOptions = <
  TError = ErrorModel | ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof teamsUsersCreate>>,
    TError,
    { teamId: string; data: CreateTeamUser },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof teamsUsersCreate>>,
  TError,
  { teamId: string; data: CreateTeamUser },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof teamsUsersCreate>>,
    { teamId: string; data: CreateTeamUser }
  > = (props) => {
    const { teamId, data } = props ?? {};

    return teamsUsersCreate(teamId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type TeamsUsersCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof teamsUsersCreate>>
>;
export type TeamsUsersCreateMutationBody = CreateTeamUser;
export type TeamsUsersCreateMutationError = ErrorModel | ProblemDetails;

export const useTeamsUsersCreate = <
  TError = ErrorModel | ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof teamsUsersCreate>>,
    TError,
    { teamId: string; data: CreateTeamUser },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof teamsUsersCreate>>,
  TError,
  { teamId: string; data: CreateTeamUser },
  TContext
> => {
  const mutationOptions = getTeamsUsersCreateMutationOptions(options);

  return useMutation(mutationOptions);
};

export const teamsUsersUpdate = (
  teamId: string,
  userId: string,
  updateTeamUser: UpdateTeamUser
) => {
  return authAxiosInstance<void>({
    url: `/teams/${teamId}/users/${userId}`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: updateTeamUser
  });
};

export const getTeamsUsersUpdateMutationOptions = <
  TError = ErrorModel | ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof teamsUsersUpdate>>,
    TError,
    { teamId: string; userId: string; data: UpdateTeamUser },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof teamsUsersUpdate>>,
  TError,
  { teamId: string; userId: string; data: UpdateTeamUser },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof teamsUsersUpdate>>,
    { teamId: string; userId: string; data: UpdateTeamUser }
  > = (props) => {
    const { teamId, userId, data } = props ?? {};

    return teamsUsersUpdate(teamId, userId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type TeamsUsersUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof teamsUsersUpdate>>
>;
export type TeamsUsersUpdateMutationBody = UpdateTeamUser;
export type TeamsUsersUpdateMutationError = ErrorModel | ProblemDetails;

export const useTeamsUsersUpdate = <
  TError = ErrorModel | ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof teamsUsersUpdate>>,
    TError,
    { teamId: string; userId: string; data: UpdateTeamUser },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof teamsUsersUpdate>>,
  TError,
  { teamId: string; userId: string; data: UpdateTeamUser },
  TContext
> => {
  const mutationOptions = getTeamsUsersUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};

export const teamsUsersDelete = (teamId: string, userId: string) => {
  return authAxiosInstance<void>({
    url: `/teams/${teamId}/users/${userId}`,
    method: "DELETE"
  });
};

export const getTeamsUsersDeleteMutationOptions = <
  TError = ErrorModel | ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof teamsUsersDelete>>,
    TError,
    { teamId: string; userId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof teamsUsersDelete>>,
  TError,
  { teamId: string; userId: string },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof teamsUsersDelete>>,
    { teamId: string; userId: string }
  > = (props) => {
    const { teamId, userId } = props ?? {};

    return teamsUsersDelete(teamId, userId);
  };

  return { mutationFn, ...mutationOptions };
};

export type TeamsUsersDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof teamsUsersDelete>>
>;

export type TeamsUsersDeleteMutationError = ErrorModel | ProblemDetails;

export const useTeamsUsersDelete = <
  TError = ErrorModel | ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof teamsUsersDelete>>,
    TError,
    { teamId: string; userId: string },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof teamsUsersDelete>>,
  TError,
  { teamId: string; userId: string },
  TContext
> => {
  const mutationOptions = getTeamsUsersDeleteMutationOptions(options);

  return useMutation(mutationOptions);
};

export const userGet = (signal?: AbortSignal) => {
  return authAxiosInstance<CurrentUserModel>({
    url: `/user`,
    method: "GET",
    signal
  });
};

export const getUserGetQueryKey = () => {
  return [`/user`] as const;
};

export const getUserGetQueryOptions = <
  TData = Awaited<ReturnType<typeof userGet>>,
  TError = unknown
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof userGet>>, TError, TData>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUserGetQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof userGet>>> = ({
    signal
  }) => userGet(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof userGet>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UserGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof userGet>>
>;
export type UserGetQueryError = unknown;

export const useUserGet = <
  TData = Awaited<ReturnType<typeof userGet>>,
  TError = unknown
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof userGet>>, TError, TData>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getUserGetQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const userUpdate = (updateUserModel: UpdateUserModel) => {
  return authAxiosInstance<void>({
    url: `/user`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: updateUserModel
  });
};

export const getUserUpdateMutationOptions = <
  TError = ErrorModel,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userUpdate>>,
    TError,
    { data: UpdateUserModel },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userUpdate>>,
  TError,
  { data: UpdateUserModel },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userUpdate>>,
    { data: UpdateUserModel }
  > = (props) => {
    const { data } = props ?? {};

    return userUpdate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof userUpdate>>
>;
export type UserUpdateMutationBody = UpdateUserModel;
export type UserUpdateMutationError = ErrorModel;

export const useUserUpdate = <
  TError = ErrorModel,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userUpdate>>,
    TError,
    { data: UpdateUserModel },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof userUpdate>>,
  TError,
  { data: UpdateUserModel },
  TContext
> => {
  const mutationOptions = getUserUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};

export const userChangePassword = (
  changePasswordModel: ChangePasswordModel
) => {
  return authAxiosInstance<void>({
    url: `/user/change-password`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: changePasswordModel
  });
};

export const getUserChangePasswordMutationOptions = <
  TError = ErrorModel,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userChangePassword>>,
    TError,
    { data: ChangePasswordModel },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userChangePassword>>,
  TError,
  { data: ChangePasswordModel },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userChangePassword>>,
    { data: ChangePasswordModel }
  > = (props) => {
    const { data } = props ?? {};

    return userChangePassword(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserChangePasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof userChangePassword>>
>;
export type UserChangePasswordMutationBody = ChangePasswordModel;
export type UserChangePasswordMutationError = ErrorModel;

export const useUserChangePassword = <
  TError = ErrorModel,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userChangePassword>>,
    TError,
    { data: ChangePasswordModel },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof userChangePassword>>,
  TError,
  { data: ChangePasswordModel },
  TContext
> => {
  const mutationOptions = getUserChangePasswordMutationOptions(options);

  return useMutation(mutationOptions);
};
