### Add asset
GET https://localhost:5001/api/assets
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "test",
  "deviceTypeId": 10,
  "deviceId": "1234567891234567"
}

### Invalid device type
POST https://localhost:5001/api/assets
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "test",
  "deviceTypeId": 12312423,
  "deviceId": "1234567891234567"
}

### Empty name
POST https://localhost:5001/api/assets
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "",
  "deviceTypeId": 10,
  "deviceId": "1234567891234567"
}

### Empty device id
POST https://localhost:5001/api/assets
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Abcd",
  "deviceTypeId": 10,
  "deviceId": ""
}
