### Rename asset
POST https://localhost:5001/api/assets/1/settings/rename
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "testssdsfsdfs"
}

### Empty name
POST https://localhost:5001/api/assets/1/settings/rename
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": ""
}

### Invalid asset id
POST https://localhost:5001/api/assets/12345/settings/rename
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "testssdsfsdfs"
}