### Wrong asset id
PUT https://localhost:5001/api/assets/100/device
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "deviceId": "1234567890",
  "deviceTypeId": 718
}

### Empty device id
PUT https://localhost:5001/api/assets/57/device
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "deviceId": "12345",
  "deviceTypeId": 10
}

### Empty device type id
PUT https://localhost:5001/api/assets/57/device
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "deviceId": "1234567890",
}

### Wrong device type id
PUT https://localhost:5001/api/assets/57/device
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "deviceId": "123456789",
  "deviceTypeId": 71812343
}