/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */
import type { ListModelOfAssetStatItemModel } from "./listModelOfAssetStatItemModel";
import type { AssetStatListModelAllOf } from "./assetStatListModelAllOf";

export type AssetStatListModel = ListModelOfAssetStatItemModel &
  AssetStatListModelAllOf;
