/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */

export type AssetsMessagesGetListParams = {
  /**
   * @nullable
   */
  StartDate?: string | null;
  /**
   * @nullable
   */
  EndDate?: string | null;
  /**
   * @nullable
   */
  MinAltitude?: number | null;
  /**
   * @nullable
   */
  MaxAltitude?: number | null;
  /**
   * @nullable
   */
  MinSpeed?: number | null;
  /**
   * @nullable
   */
  MaxSpeed?: number | null;
  /**
   * @nullable
   */
  Latitude?: number | null;
  /**
   * @nullable
   */
  Longitude?: number | null;
  /**
   * @nullable
   */
  Radius?: number | null;
  page?: number;
  /**
   * @minimum 0
   * @maximum 10000
   */
  size?: number;
};
