/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */

export interface AssetStatsModel {
  /** @nullable */
  distance?: number | null;
  /** @nullable */
  distancePrevious?: number | null;
  /** @nullable */
  duration?: number | null;
  /** @nullable */
  durationPrevious?: number | null;
  /** @nullable */
  fuelConsumption?: number | null;
  /** @nullable */
  fuelConsumptionPrevious?: number | null;
  /** @nullable */
  fuelConsumptionAverage?: number | null;
  /** @nullable */
  fuelConsumptionAveragePrevious?: number | null;
}
