/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */

export type AssetStatsPeriod =
  (typeof AssetStatsPeriod)[keyof typeof AssetStatsPeriod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AssetStatsPeriod = {
  Day: "Day",
  Week: "Week",
  Month: "Month",
  Year: "Year"
} as const;
