/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */
import type { AssetUserRole } from "./assetUserRole";

export interface AssetUserModel {
  id?: string;
  /** @minLength 1 */
  email: string;
  userRole: AssetUserRole;
  /** @minLength 1 */
  userId: string;
  /** @minLength 1 */
  createdDate: string;
}
