/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */
import type { AssetModelLastMessage } from "./assetModelLastMessage";
import type { AssetModelLastPositionMessage } from "./assetModelLastPositionMessage";
import type { AssetModelDevice } from "./assetModelDevice";

export interface AssetModel {
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  organizationId: string;
  online: boolean;
  maxSpeed: number;
  /** @nullable */
  lastMessage?: AssetModelLastMessage;
  /** @nullable */
  lastPositionMessage?: AssetModelLastPositionMessage;
  /** @nullable */
  device?: AssetModelDevice;
}
