/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */

export type AssetStatsDateRange =
  (typeof AssetStatsDateRange)[keyof typeof AssetStatsDateRange];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AssetStatsDateRange = {
  Today: "Today",
  ThisWeek: "ThisWeek",
  ThisMonth: "ThisMonth",
  ThisYear: "ThisYear"
} as const;
