/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */

export type AssetsTripsGetListParams = {
  /**
   * @nullable
   */
  MinAvgAltitude?: number | null;
  /**
   * @nullable
   */
  MaxAvgAltitude?: number | null;
  /**
   * @nullable
   */
  MinAvgSpeed?: number | null;
  /**
   * @nullable
   */
  MaxAvgSpeed?: number | null;
  /**
   * @nullable
   */
  MinDuration?: number | null;
  /**
   * @nullable
   */
  MaxDuration?: number | null;
  /**
   * @nullable
   */
  Latitude?: number | null;
  /**
   * @nullable
   */
  Longitude?: number | null;
  /**
   * @nullable
   */
  Radius?: number | null;
  /**
   * @nullable
   */
  StartDate?: string | null;
  /**
   * @nullable
   */
  EndDate?: string | null;
};
