/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */

export interface BasePasswordModel {
  /** @minLength 1 */
  password: string;
  /** @minLength 1 */
  confirmPassword: string;
}
