/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */

export interface CreateAccountModel {
  /** @nullable */
  captcha?: string | null;
  /** @minLength 1 */
  confirmPassword: string;
  /** @minLength 1 */
  email: string;
  /** @minLength 1 */
  password: string;
}
