/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */

export interface CreateAssetModel {
  /** @minLength 1 */
  deviceTypeId: string;
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  serialNumber: string;
}
