/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */

export interface CreateOrUpdateAssetDeviceModel {
  /** @minLength 1 */
  serialNumber: string;
  /** @minLength 1 */
  deviceTypeId: string;
}
