/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */
import type { UnitsType } from "./unitsType";
import type { UserAssetModel } from "./userAssetModel";
import type { UserOrganizationModel } from "./userOrganizationModel";
import type { UserAuthenticationModel } from "./userAuthenticationModel";

export interface CurrentUserModel {
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  email: string;
  units: UnitsType;
  assets?: UserAssetModel[];
  organizations?: UserOrganizationModel[];
  authentication?: UserAuthenticationModel;
}
