/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */
import type { UserAssetModel } from "./userAssetModel";
import type { UserAuthenticationModel } from "./userAuthenticationModel";
import type { UserOrganizationModel } from "./userOrganizationModel";
import type { UnitsType } from "./unitsType";

export interface CurrentUserModel {
  assets?: UserAssetModel[];
  authentication?: UserAuthenticationModel;
  /** @minLength 1 */
  email: string;
  /** @minLength 1 */
  id: string;
  organizations?: UserOrganizationModel[];
  units: UnitsType;
}
