/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */
import type { DeviceTypeModel } from "./deviceTypeModel";

export interface DeviceModel {
  active: boolean;
  deviceType: DeviceTypeModel;
  /** @minLength 1 */
  id: string;
  /** @nullable */
  positions?: number | null;
  /** @minLength 1 */
  serialNumber: string;
}
