/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */
import type { DeviceMessageModelDevice } from "./deviceMessageModelDevice";
import type { DeviceMessageModelGsm } from "./deviceMessageModelGsm";
import type { PositionDataModel } from "./positionDataModel";
import type { DeviceMessageModelPriority } from "./deviceMessageModelPriority";
import type { DeviceMessageModelVehicle } from "./deviceMessageModelVehicle";

export interface DeviceMessageModel {
  createdDate?: string;
  /** @nullable */
  device?: DeviceMessageModelDevice;
  /** @nullable */
  gsm?: DeviceMessageModelGsm;
  id?: string;
  position: PositionDataModel;
  /** @nullable */
  priority?: DeviceMessageModelPriority;
  /** @nullable */
  vehicle?: DeviceMessageModelVehicle;
}
