/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */
import type { DeviceMessageModelPriority } from "./deviceMessageModelPriority";
import type { PositionDataModel } from "./positionDataModel";
import type { DeviceMessageModelDevice } from "./deviceMessageModelDevice";
import type { DeviceMessageModelVehicle } from "./deviceMessageModelVehicle";
import type { DeviceMessageModelGsm } from "./deviceMessageModelGsm";

export interface DeviceMessageModel {
  id?: string;
  createdDate?: string;
  /** @nullable */
  priority?: DeviceMessageModelPriority;
  position: PositionDataModel;
  /** @nullable */
  device?: DeviceMessageModelDevice;
  /** @nullable */
  vehicle?: DeviceMessageModelVehicle;
  /** @nullable */
  gsm?: DeviceMessageModelGsm;
}
