/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */
import type { VehicleDataModel } from "./vehicleDataModel";

/**
 * @nullable
 */
export type DeviceMessageModelVehicle = VehicleDataModel | null;
