/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */

export interface DeviceDataModel {
  /** @nullable */
  odometer?: number | null;
  /** @nullable */
  batteryLevel?: number | null;
  /** @nullable */
  batteryVoltage?: number | null;
  /** @nullable */
  batteryCurrent?: number | null;
}
