/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */
import type { ProtocolModel } from "./protocolModel";

export interface DeviceTypeModel {
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  manufacturer: string;
  /** @minLength 1 */
  model: string;
  /** @minLength 1 */
  displayName: string;
  protocol: ProtocolModel;
}
