/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */

export interface DistanceReportItemModel {
  /** @minLength 1 */
  date: string;
  distance: number;
  duration: number;
  averageSpeed: number;
  maxSpeed: number;
}
