/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */

export interface DistanceReportItemModel {
  averageSpeed: number;
  /** @minLength 1 */
  date: string;
  distance: number;
  duration: number;
  maxSpeed: number;
}
