/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorModelErrors } from "./errorModelErrors";

export interface ErrorModel {
  code?: string;
  /** @nullable */
  errors?: ErrorModelErrors;
  /** @nullable */
  message?: string | null;
}
