/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */

export interface FuelConsumptionReportItemModel {
  /** @nullable */
  averageFuelConsumption?: number | null;
  /** @nullable */
  averageSpeed?: number | null;
  /** @minLength 1 */
  date: string;
  distance: number;
  duration: number;
  /** @nullable */
  fuelConsumption?: number | null;
}
