/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */

export type FuelConsumptionReportModelAllOf = {
  averageFuelConsumption: number;
  averageSpeed: number;
  totalDistance: number;
  totalDuration: number;
  totalFuelConsumption: number;
};
