/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */
import type { ListModelOfFuelConsumptionReportItemModel } from "./listModelOfFuelConsumptionReportItemModel";
import type { FuelConsumptionReportModelAllOf } from "./fuelConsumptionReportModelAllOf";

export type FuelConsumptionReportModel =
  ListModelOfFuelConsumptionReportItemModel & FuelConsumptionReportModelAllOf;
