/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */

export interface GsmDataModel {
  /** @nullable */
  signalLevel?: number | null;
  /** @nullable */
  mobileCountryCode?: string | null;
  /** @nullable */
  mobileNetworkCode?: string | null;
}
