/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */
import type { TeamAssetModel } from "./teamAssetModel";

export interface ListModelOfTeamAssetModel {
  items: TeamAssetModel[];
}
