/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */
import type { AssetModel } from "./assetModel";

export interface ListModelOfAssetModel {
  items: AssetModel[];
}
