/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */

export interface LocationModel {
  /** @nullable */
  city?: string | null;
  /** @nullable */
  country?: string | null;
  /** @nullable */
  county?: string | null;
  displayName?: string;
  /** @nullable */
  postalCode?: string | null;
  /** @nullable */
  state?: string | null;
  /** @nullable */
  street?: string | null;
  /** @nullable */
  suburb?: string | null;
  /** @nullable */
  town?: string | null;
  /** @nullable */
  village?: string | null;
}
