/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */
import type { MessageDeviceProperty } from "./messageDeviceProperty";
import type { MessageGsmProperty } from "./messageGsmProperty";
import type { MessagePosition } from "./messagePosition";
import type { MessagePriorityProperty } from "./messagePriorityProperty";
import type { MessageVehicleProperty } from "./messageVehicleProperty";

export interface Message {
  createdDate?: string;
  /** @nullable */
  device?: MessageDeviceProperty;
  /** @nullable */
  gsm?: MessageGsmProperty;
  id?: string;
  position: MessagePosition;
  /** @nullable */
  priority?: MessagePriorityProperty;
  /** @nullable */
  vehicle?: MessageVehicleProperty;
}
