/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */
import type { ListOfMessage } from "./listOfMessage";
import type { MessageListAllOf } from "./messageListAllOf";

export type MessageList = ListOfMessage & MessageListAllOf;
