/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */

export type MessageListAllOf = {
  /** @nullable */
  averageSpeed?: number | null;
  /** @nullable */
  averageAltitude?: number | null;
  totalCount: number;
};
