/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */

export type MessagePriority =
  (typeof MessagePriority)[keyof typeof MessagePriority];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessagePriority = {
  Low: "Low",
  Medium: "Medium",
  High: "High",
  Emergency: "Emergency"
} as const;
