/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */
import type { ListModelOfDeviceMessageModel } from "./listModelOfDeviceMessageModel";
import type { MessageListAllOf } from "./messageListAllOf";

export type MessageList = ListModelOfDeviceMessageModel & MessageListAllOf;
