/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */

export interface MessageGsm {
  /** @nullable */
  mobileCountryCode?: string | null;
  /** @nullable */
  mobileNetworkCode?: string | null;
  /** @nullable */
  signalLevel?: number | null;
}
