/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */

export interface MessageVehicle {
  /** @nullable */
  ignition?: boolean | null;
  /** @nullable */
  odometer?: number | null;
  /** @nullable */
  voltage?: number | null;
}
