/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */

export interface OrganizationModel {
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  name: string;
  assetsCount: number;
  usersCount: number;
  teamsCount: number;
}
