/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */
import type { LatLong } from "./latLong";

export interface PositionDataModel {
  coordinates: LatLong;
  /** @minLength 1 */
  date: string;
  speed?: number;
  heading?: number;
  altitude?: number;
  satellites?: number;
  hdop?: number;
  /** @nullable */
  pdop?: number | null;
  valid?: boolean;
}
