/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */
import type { BasePasswordModel } from "./basePasswordModel";
import type { ResetPasswordModelAllOf } from "./resetPasswordModelAllOf";

export type ResetPasswordModel = BasePasswordModel & ResetPasswordModelAllOf;
