/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */
import type { BasePasswordModel } from "./basePasswordModel";
import type { ResetPasswordAllOf } from "./resetPasswordAllOf";

export type ResetPassword = BasePasswordModel & ResetPasswordAllOf;
