/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */

export interface TeamAssetModel {
  /** @minLength 1 */
  assetId: string;
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  createdDate: string;
}
