/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */

export type TeamUserRole = (typeof TeamUserRole)[keyof typeof TeamUserRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TeamUserRole = {
  Owner: "Owner",
  Member: "Member"
} as const;
