/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */
import type { ListModelOfTrip } from "./listModelOfTrip";
import type { TripListAllOf } from "./tripListAllOf";

export type TripList = ListModelOfTrip & TripListAllOf;
