/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */
import type { PositionDataModel } from "./positionDataModel";

export interface TripReportItemModel {
  /** @nullable */
  averageFuelConsumption?: number | null;
  /** @nullable */
  averageSpeed?: number | null;
  distance?: number;
  duration?: number;
  endPosition: PositionDataModel;
  /** @nullable */
  fuelConsumption?: number | null;
  /** @nullable */
  maxSpeed?: number | null;
  startPosition: PositionDataModel;
}
