/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */

export type TripListModelAllOf = {
  totalDistance: number;
  totalDuration: number;
  totalPositions: number;
  averageSpeed: number;
  maxSpeed: number;
  averageAltitude: number;
  maxAltitude: number;
  /** @nullable */
  fuelConsumption?: number | null;
  /** @nullable */
  averageFuelConsumption?: number | null;
};
