/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */
import type { PositionDataModel } from "./positionDataModel";

export interface Trip {
  positions: PositionDataModel[];
  startPosition: PositionDataModel;
  endPosition: PositionDataModel;
  duration: number;
  distance: number;
  /** @nullable */
  fuelConsumption?: number | null;
  /** @nullable */
  maxSpeed?: number | null;
  /** @nullable */
  averageSpeed?: number | null;
  /** @nullable */
  averageAltitude?: number | null;
  /** @nullable */
  averageFuelConsumption?: number | null;
}
