/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */
import type { ListOfTripReportItem } from "./listOfTripReportItem";
import type { TripReportAllOf } from "./tripReportAllOf";

export type TripReport = ListOfTripReportItem & TripReportAllOf;
