/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */

export type TripListModelAllOf = {
  totalDistance: number;
  totalDuration: number;
  totalPositions: number;
  avgSpeed: number;
  avgAltitude: number;
  maxSpeed: number;
};
