/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */
import type { MessagePosition } from "./messagePosition";

export interface Trip {
  /** @nullable */
  averageAltitude?: number | null;
  /** @nullable */
  averageFuelConsumption?: number | null;
  /** @nullable */
  averageSpeed?: number | null;
  distance: number;
  duration: number;
  endPosition: MessagePosition;
  /** @nullable */
  fuelConsumption?: number | null;
  /** @nullable */
  maxSpeed?: number | null;
  positions: MessagePosition[];
  startPosition: MessagePosition;
}
