/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */
import type { ListModelOfTripReportItemModel } from "./listModelOfTripReportItemModel";
import type { TripReportModelAllOf } from "./tripReportModelAllOf";

export type TripReportModel = ListModelOfTripReportItemModel &
  TripReportModelAllOf;
