/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */

export type TripReportModelAllOf = {
  totalDistance: number;
  totalDuration: number;
  totalFuelConsumption: number;
  averageFuelConsumption: number;
  averageSpeed: number;
  maxSpeed: number;
};
