/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateUserModelUnitsType } from "./updateUserModelUnitsType";

export interface UpdateUserModel {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  unitsType?: UpdateUserModelUnitsType;
}
