/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */

export interface VehicleDataModel {
  /** @nullable */
  odometer?: number | null;
  /** @nullable */
  ignition?: boolean | null;
  /** @nullable */
  voltage?: number | null;
}
