/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */
import type { DayOfWeek } from "./dayOfWeek";

export interface WorkScheduleDayModel {
  dayOfWeek: DayOfWeek;
  startTime?: string;
  endTime?: string;
}
