namespace Navtrack.Listener.Protocols.Meitrack
{
    public enum Event
    {
        Input1Active = 1,
        Input2Active = 2,
        Input3Active = 3,
        Input4Active = 4,
        Input5Active = 5,
        Input1Inactive = 9,
        Input2Inactive = 10,
        Input3Inactive = 11,
        Input4Inactive = 12,
        Input5Inactive = 13,
        LowBattery = 17,
        LowExternalPower = 18,
        Speeding = 19,
        EnterGeofence = 20,
        ExitGeoFence = 21,
        ExternalPowerOn = 22,
        ExternalPowerOff = 23,
        NoGPSSignal = 24,
        GetGPSSignal = 25,
        EnterSleep = 26,
        ExitSleep = 27,
        GPSAntennaCut = 28,
        DeviceReboot = 29,
        Impact = 30,
        HeartbeatReport = 31,
        HeadingChangeReport = 32,
        DistanceIntervalReport = 33,
        CurrentLocationReport = 34,
        TimeIntervalReport = 35,
        TowAlarm = 36,
        RFID = 37,
        GetAddressFromServer = 38,
        Picture = 39,
        PressInput1ToCall = 65,
        PressInput2ToCall = 66,
        PressInput3ToCall = 67,
        PressInput4ToCall = 68,
        PressInput5ToCall = 69,
        RejectIncomingCall = 70,
        ReportLocationAfterCallingIn = 71,
        AutoAnswerIncomingCall = 72,
        ListenIn = 73
    }
}