name: Docker build

on:
  push:
    tags:
      - "v*"

env:
  version: ${GITHUB_REF_NAME#v}

concurrency:
  group: publish
  cancel-in-progress: true

jobs:
  build:
    if: github.repository == 'navtrack/navtrack'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker build and push
        run: |
          docker buildx build -t ghcr.io/navtrack/web:${{ env.version }} --platform linux/amd64,linux/arm64 -f frontend/Dockerfile --push --provenance=false frontend
          docker buildx build -t ghcr.io/navtrack/api:${{ env.version }} --platform linux/amd64,linux/arm64 -f backend/Navtrack.Api/Dockerfile --push --provenance=false .
          docker buildx build -t ghcr.io/navtrack/listener:${{ env.version }} --platform linux/amd64,linux/arm64 -f backend/Navtrack.Listener/Dockerfile --push --provenance=false .
