name: Publish Docker Images

on:
  release:
    types: [released]

concurrency:
  group: main
  cancel-in-progress: true

jobs:
  publish:
    if: github.repository == 'navtrack/navtrack'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GHCR
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker build
        run: |
          ./build-docker-images.sh
      - name: Release version
        run: |
          TAG=${{ github.event.release.tag_name }}
          VERSION=${TAG#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Docker tag
        run: |
          docker tag navtrack/api ghcr.io/navtrack/navtrack/api:latest
          docker tag navtrack/api ghcr.io/navtrack/navtrack/api:${{ env.VERSION }}
          docker tag navtrack/web ghcr.io/navtrack/navtrack/web:latest
          docker tag navtrack/web ghcr.io/navtrack/navtrack/web:${{ env.VERSION }}
          docker tag navtrack/listener ghcr.io/navtrack/navtrack/listener:latest
          docker tag navtrack/listener ghcr.io/navtrack/navtrack/listener:${{ env.VERSION }}
      - name: Docker push
        run: |
          docker push --all-tags ghcr.io/navtrack/navtrack/api
          docker push --all-tags ghcr.io/navtrack/navtrack/web
          docker push --all-tags ghcr.io/navtrack/navtrack/listener
